#!/bin/sh
# This is a black-box test for the installed-skill helper. It puts a fake
# code-annotator executable first on PATH and observes only its arguments and
# the helper's stdout/exit status.
set -eu

# Resolve the repository root so the test works from any current directory.
project_dir=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
poller="$project_dir/.agents/skills/code-annotator/scripts/poll-agent-queue.sh"

# All state lives in a temporary directory and is removed even if the test is
# interrupted. No repository files are used as test state.
test_dir=$(mktemp -d "${TMPDIR:-/tmp}/code-annotator-poll-test.XXXXXX")
trap 'rm -rf "$test_dir"' EXIT INT TERM
mkdir "$test_dir/bin"

# The fake CLI implements only the agent subcommands the poller needs. It logs
# every invocation so the assertions can verify discovery and ETag handoff.
cat >"$test_dir/bin/code-annotator" <<'EOF'
#!/bin/sh
set -eu
log=${POLL_TEST_LOG:?}
printf '%s\n' "$*" >>"$log"

# In retry mode, fail the first request only. The poller should retain its
# previous ETag, wait, and invoke the CLI again.
if [ -n "${POLL_TEST_RETRY:-}" ]; then
    count_file=${POLL_TEST_COUNT_FILE:?}
    count=$(cat "$count_file" 2>/dev/null || echo 0)
    count=$((count + 1))
    printf '%s\n' "$count" >"$count_file"
    if [ "$count" -eq 1 ]; then
        exit 1
    fi
fi

# Discovery must return only a loopback viewer URL. The poller is responsible
# for passing --root here; queue calls use the discovered URL instead.
if [ "$2" = discover ]; then
    printf '{"url":"http://127.0.0.1:54321"}\n'
    exit 0
fi

# Read the conditional-poll argument while ignoring unrelated CLI flags. The
# real CLI accepts the same flag order generated by the helper.
etag=''
root=''
while [ "$#" -gt 0 ]; do
    case "$1" in
        --etag) etag=$2; shift 2 ;;
        --root) root=$2; shift 2 ;;
        *) shift ;;
    esac
done

# The root is checked only during discovery. This catches accidental loss or
# misrouting of the caller's disambiguation argument.
if [ -n "$root" ] && [ "$root" != "$POLL_TEST_ROOT" ]; then
    echo "unexpected root: $root" >&2
    exit 1
fi

# ETag 0 represents the first forced miss. ETag e1 represents an unchanged
# second poll; terminate the parent after returning it so the test can inspect
# both iterations without leaving an infinite watcher running.
if [ "$etag" = 0 ]; then
    printf '%s\n' '{"etag":"e1","modified":true,"queue":{"schemaVersion":1,"documents":[{"path":"README.md"}]}}'
elif [ "$etag" = e1 ]; then
    printf '%s\n' '{"etag":"e1","modified":false}'
    kill -TERM "$PPID"
else
    echo "unexpected etag: $etag" >&2
    exit 1
fi
EOF
chmod 0755 "$test_dir/bin/code-annotator"

# The first scenario covers discovery, --root, the stale sentinel, --once, and
# the rule that stdout contains the raw queue object rather than the envelope.
log="$test_dir/calls"
root="$test_dir/content"
mkdir "$root"

output=$(PATH="$test_dir/bin:$PATH" POLL_TEST_LOG="$log" POLL_TEST_ROOT="$root" \
    "$poller" --root "$root" --interval 0 --once)
[ "$output" = '{"schemaVersion":1,"documents":[{"path":"README.md"}]}' ]
grep -F -- 'discover --root ' "$log" >/dev/null
grep -F -- 'queue --url http://127.0.0.1:54321 --status open,needs_changes --etag 0' "$log" >/dev/null

# The second scenario starts with a known URL and verifies ETag carry-forward.
# The fake exits the parent watcher after its unchanged response.
set +e
PATH="$test_dir/bin:$PATH" POLL_TEST_LOG="$log" POLL_TEST_ROOT="$root" \
    "$poller" --url http://127.0.0.1:54321 --interval 0 >"$test_dir/loop-output"
exit_code=$?
set -e
[ "$exit_code" -eq 130 ]
[ "$(sed -n '1p' "$test_dir/loop-output")" = '{"schemaVersion":1,"documents":[{"path":"README.md"}]}' ]
grep -F -- 'queue --url http://127.0.0.1:54321 --status open,needs_changes --etag e1' "$log" >/dev/null
[ "$(wc -l <"$test_dir/loop-output" | tr -d ' ')" -eq 1 ]

# The final scenario injects one failed queue request, then verifies the
# continuous watcher retries and eventually reaches the same termination path.
retry_count="$test_dir/retry-count"
printf '0\n' >"$retry_count"
set +e
PATH="$test_dir/bin:$PATH" POLL_TEST_LOG="$log" POLL_TEST_ROOT="$root" \
    POLL_TEST_RETRY=1 POLL_TEST_COUNT_FILE="$retry_count" \
    "$poller" --url http://127.0.0.1:54321 --interval 0 >"$test_dir/retry-output"
exit_code=$?
set -e
[ "$exit_code" -eq 130 ]
[ "$(cat "$retry_count")" -eq 3 ]

# A single success line confirms all three scenarios completed.
echo 'poll-agent-queue tests passed'
